# Generated by Django 4.1.7 on 2023-03-23 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systemsdb', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('locationsdb', '0001_initial'),
        ('devicesdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_instance', models.PositiveIntegerField(blank=True, null=True, verbose_name='Internal index')),
                ('sn_internal_text', models.CharField(blank='True', max_length=200, verbose_name='SN internal')),
                ('sn_manufacturer_text', models.CharField(blank='True', max_length=200, verbose_name='SN manufacturer')),
                ('order_text', models.CharField(blank='True', max_length=200, verbose_name='Order number')),
                ('reception_date', models.DateField(verbose_name='Reception date')),
                ('entry_date', models.DateField(auto_now_add=True, verbose_name='Entry date')),
                ('lastupdate', models.DateField(auto_now=True, verbose_name='Last update')),
                ('location', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='locationsdb.location')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devicesdb.reference')),
                ('system_ref', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='systemsdb.basesystem')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('instance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='instancesdb.instance')),
                ('install_date', models.DateField(verbose_name='Installation date')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('instancesdb.instance',),
        ),
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('instance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='instancesdb.instance')),
                ('device_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instancesdb.device')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('instancesdb.instance',),
        ),
    ]
