# Generated by Django 4.1.7 on 2023-03-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationsdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='code_text',
            field=models.CharField(blank='True', max_length=2, verbose_name='Code text'),
        ),
    ]
