# Generated by Django 4.1.7 on 2023-03-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationsdb', '0002_zone_code_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='index_int',
            field=models.IntegerField(default=1, verbose_name='Index'),
            preserve_default=False,
        ),
    ]
