# Generated by Django 4.1.7 on 2023-03-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsdb', '0002_basesystem_code_text_groupsystem_code_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsystem',
            name='code_text',
            field=models.CharField(blank='True', max_length=1, verbose_name='Code text'),
        ),
    ]
