# Generated by Django 4.1.7 on 2023-03-23 05:49

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('AQ', 'Part of a new company'), ('LQ', 'Not active anymore'), ('UN', 'Unknown')], default='UN', max_length=2)),
                ('website_url', models.URLField(blank=True, verbose_name='Manufacturer website')),
                ('entry_date', models.DateField(auto_now_add=True, verbose_name='Entry date')),
                ('lastupdate', models.DateField(auto_now=True, verbose_name='Last update')),
                ('new_manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devicesdb.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
                ('ref_manufacturer_text', models.CharField(blank='True', max_length=200)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('NN', 'Not recommanded for new desing'), ('OB', 'Obsolete'), ('UN', 'Unknown')], default='UN', max_length=2)),
                ('solution', models.CharField(choices=[('CO', 'Commercial off-the-shelf'), ('CU', 'Custom made'), ('OT', 'Other/Unknow')], default='CO', max_length=2)),
                ('EoL_date', models.DateField(blank=True, null=True, verbose_name='End of Life date')),
                ('website_url', models.URLField(blank=True, verbose_name='Webpage of the item')),
                ('entry_date', models.DateField(auto_now_add=True, verbose_name='Entry date')),
                ('lastupdate', models.DateField(auto_now=True, verbose_name='Last update')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devicesdb.manufacturer')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
